#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
sudo -v #ask password beforehand
source $SCRIPT_DIR/functions

case $1 in
    terminal)
        echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
        read -p 'Answer: '  reply
        if [[ $reply =~ ^[Yy]$ ]]
        then
            install_dependencies && setup_zsh && setup_tmux && setup_vim
        fi
        ;;

    dev_deps)
        # Install coding dependencies
        read -p "Installer les dependances de dev (Y/n)?" dev_deps
        dev_deps=${dev_deps:-Y}
        if [ "$dev_deps" != "${dev_deps#[Yy]}" ] ;then
            install_docker
            install_dev_dependencies
        fi
        ;;
  
    i3)
        if [[ "$OSTYPE" == "linux"* ]]; then
            setup_i3
        fi
        ;;

    *)
        echo "boostrap: [terminal|dev_deps|i3]"   
        ;;
esac
