#!/usr/bin/env bash

set -e

if [ -z "$DOTFILES_PATH" ]; then
    echo "DOTFILES_PATH is not set. Please set it to the path of your dotfiles dir"
    exit 1
fi

sudo -v #ask password beforehand
source $DOTFILES_PATH/functions

case $1 in
    terminal)
        echo 'This will reset your terminal. Are you sure you want to to this? (y/n) '
        read -p 'Answer: '  reply
        if [[ $reply =~ ^[Yy]$ ]]
        then
            install_dependencies
            setup_zsh
            setup_tmux
            setup_vim
        fi
        ;;

    dev_deps)
        # Install coding dependencies
        read -p "Installer les dependances de dev (Y/n)?" dev_deps
        dev_deps=${dev_deps:-Y}
        if [ "$dev_deps" != "${dev_deps#[Yy]}" ] ;then
            install_docker
            install_dev_dependencies
        fi
        ;;

    sway)
        if [[ "$OSTYPE" == "linux"* ]]; then
            setup_sway
        fi
        ;;

    hyperland)
        if [[ "$OSTYPE" == "linux"* ]]; then
            setup_hyprland
        fi
        ;;

    *)
        echo "boostrap: [terminal|dev_deps|sway|hyprland]"
        ;;
esac
