#!/usr/bin/env zsh

# This script is used to kill the Hyprland process if it is running 
# as disptach exit doesn't work properly in some cases. 
if  pgrep -x Hyprland > /dev/null; then
    hyprctl dispatch exit 0
    sleep 2
    if pgrep -x Hyprland > /dev/null; then 
        killall -9 Hyprland
    fi
fi
