#!/usr/bin/env sh 

CONFIG_PATH=$1

pkill -x waybar

if [ -f "$WAYBAR_CONFIG_PATH" ]; then
    USER_CONFIG=$WAYBAR_CONFIG_PATH
fi

if [ -f "$WAYBAR_STYLE_PATH" ]; then
    USER_STYLE=$WAYBAR_STYLE_PATH
fi

if [ -z "$CONFIG_PATH" ]; then
    waybar
else
    waybar -c "${USER_CONFIG:-"$CONFIG_PATH/config.jsonc"}" -s "${USER_STYLE:-"$CONFIG_PATH/style.css"}"
fi
