name = "screenshots"
name_pretty = "Screenshots"
icon = "camera-photo"
global_search = true

[[entries]]
keywords = ["screen"]
text = "View"
actions = { view = "nomacs ~/Images" }

[[entries]]
keywords = ["screen","annotate"]
text = "Annotate"
actions = { annotate = "wl-paste | swappy -f -" }

[[entries]]
keywords = ["screen","record"]
text = "Toggle Record"
actions = { toggle_screenrecord = "recorder" }

[[entries]]
keywords = ["screen", "shot"]
text = "Screenshot Region"
actions = { screenshot = "hyprshot -m region" }

[[entries]]
keywords = ["screen", "shot"]
text = "Screenshot Window"
actions = { screenshot = "hyprshot -m window" }
