[ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
v_align = "center"
spacing = 10
orientation = "vertical"

[ui.window.box.margins]
bottom = 200
top = 200

[ui.window.box.scroll]
overlay_scrolling = false

[ui.window.box.scroll.list]
always_show = true

[ui.window.box.scroll.list.item]
max_height = 400
max_width = 800
min_width = 500
marker_color = "#ee99a0"
spacing = 5

[ui.window.box.scroll.list.item.activation_label]
h_align = "end"
h_expand = true
justify = "right"
x_align = 1

[ui.window.box.scroll.list.item.icon]
theme = "Papirus"

[ui.window.box.scroll.list.item.text]
h_align = "fill"
h_expand = true
revert = true

[ui.window.box.search]
v_align = "fill"
