[ui.window.box]
width = 400
spacing = 0

[ui.window.box.margins]
bottom = 0
top = 0

[ui.window.box.scroll]
overlay_scrolling = false

[ui.window.box.scroll.list]
max_height = 1080
max_width = 350
min_width = 350
width = 350

[ui.window.box.scroll.list.item]
spacing = 0
max_height = 200
max_width = 350
min_width = 350
v_expand = false
h_expand = false

[ui.window.box.scroll.list.item.activation_label]
hide = true

[ui.window.box.scroll.list.item.icon]
theme = "Papirus"
h_expand = true
pixel_size = 350

[ui.window.box.scroll.list.item.text]
hide = true

[ui.window.box.search]
v_align = "fill"

