# Some default env vars.
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
envd = XDG_CURRENT_DESKTOP,Hyprland
envd = XDG_SESSION_DESKTOP,Hyprland
envd = XDG_SESSION_TYPE,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = HYPRSHOT_DIR,$HOME/Pictures/Screenshots
# SDL
env = SDL_VIDEODRIVER,wayland;x11
# Apps
$terminal = /usr/bin/foot
envd = TERMINAL,$terminal
envd = EDITOR,nvim
envd = XDG_UTILS_TERMINAL,$terminal
# QT
envd = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
envd = QT_QPA_PLATFORMTHEME,hyprqt6engine
envd = QT_QPA_PLATFORM,wayland;xcb
envd = QT_AUTO_SCREEN_SCALE_FACTOR,1

# User directory
envd = XDG_DESKTOP_DIR,$HOME/Desktop
envd = XDG_DOWNLOAD_DIR,$HOME/Downloads
envd = XDG_TEMPLATES_DIR,$HOME/Templates
envd = XDG_PUBLICSHARE_DIR,$HOME/Public
envd = XDG_DOCUMENTS_DIR,$HOME/Documents
envd = XDG_MUSIC_DIR,$HOME/Music
envd = XDG_PICTURES_DIR,$HOME/Pictures
envd = XDG_VIDEOS_DIR,$HOME/Videos
