hl.bind(MainMod .. " + D", hl.dsp.exec_cmd("vicinae vicinae://toggle"))
hl.bind(
    MainMod .. " + O",
    hl.dsp.exec_cmd("vicinae vicinae://launch/@rastsislaux/store.vicinae.pulseaudio/outputDevices")
)
hl.bind(MainMod .. " + V", hl.dsp.exec_cmd("vicinae vicinae://launch/clipboard/history"))
hl.bind(MainMod .. " + SHIFT + W", hl.dsp.exec_cmd("vicinae vicinae://launch/wm/switch-windows"))
hl.bind(MainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("vicinae vicinae://launch/@Yokann/twitch/streams"))
hl.bind(MainMod .. " + SHIFT + D", hl.dsp.submap("vicinae"))
hl.define_submap("vicinae", function()
    hl.bind("E", function()
        hl.dispatch(hl.dsp.exec_cmd("vicinae vicinae://launch/core/search-emojis"))
        hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("W", function()
        hl.dispatch(hl.dsp.exec_cmd("vicinae vicinae://launch/@Yokann/wallpaper-picker/select"))
        hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("escape", hl.dsp.submap("reset"))
end)
