-- Walker
hl.bind(MainMod .. " + V", hl.dsp.exec_cmd("walker -m clipboard"))
hl.bind(MainMod .. " + O", hl.dsp.exec_cmd(ConfigPath .. "/scripts/audio_switcher"))
hl.bind(MainMod .. " + SHIFT + W", hl.dsp.exec_cmd("walker -m windows"))
hl.bind(MainMod .. " + SHIFT + Y", hl.dsp.exec_cmd("walker -m menus:twitch"))
hl.bind(MainMod .. " + D", hl.dsp.exec_cmd("walker"))
hl.bind(MainMod .. " + SHIFT + D", hl.dsp.submap("walker"))
hl.define_submap("walker", function()
    hl.bind("S", function()
        hl.dispatch(hl.dsp.exec_cmd("walker -m websearch"))
        hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("F", function()
        hl.dispatch(hl.dsp.exec_cmd("walker -m finder"))
        hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("E", function()
        hl.dispatch(hl.dsp.exec_cmd("walker -m symbols"))
        hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("W", function()
        hl.dispatch(hl.dsp.exec_cmd("walker -m menus:wallpaperpicker"))
        hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("escape", hl.dsp.submap("reset"))
end)
