hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland")
    hl.exec_cmd(ConfigPath .. "/scripts/launch_hyprpaper")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("systemctl --now --user enable foot-server.socket && systemctl --now --user enable foot-server")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd(ConfigPath .. "/scripts/battery_notif")
    hl.exec_cmd("systemctl --user start hypridle.service")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd(Uwsm .. "walker --gapplication-service")
    hl.exec_cmd(ConfigPath .. "/scripts/launch_waybar")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd(ConfigPath .. "/scripts/launch_waybar")
end)
