envd = HYPR_CONFIG_PATH,$configPath
envd = WALLPAPERS_PATH,$wallpapersPath

# Home monitor configuration
# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor = FALLBACK,1920x1080@60,auto,1 # Fallback monitor  in case no other monitor is connected

$uwsm = uwsm app --
source = $configPath/autostart.conf
source = $configPath/conf.d/*.conf
source = $configPath/themes/2024/theme.conf
source = $HOME/.config/hypr/conf.d/*.conf
# Launch Waybar always after everything else
exec = $configPath/scripts/launch_waybar
