# Nvidia specific env vars
envd = GBM_BACKEND,nvidia-drm
envd = __GLX_VENDOR_LIBRARY_NAME,nvidia
envd = LIBVA_DRIVER_NAME,nvidia
envd = WLR_NO_HARDWARE_CURSORS,1

#  install libva-vdpau-driver for the line below
envd = NVD_BACKEND,direct
