#!/bin/sh

hypr=$HYPER_CONFIG_PATH
wallpaper_folder=$HOME/Images/wallpapers
wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/wallpaper/wallpaper

