#!/bin/sh

source $HYPER_CONFIG_PATH/scripts/variables/load_envs

function load_wp(){
    swww img \
        --transition-step 20 \
        --transition-type wipe \
        --transition-angle 30 \
        --transition-fps  60 \
        --transition-duration .8 \
        --transition-bezier 0.0,0.0,1.0,1.0 \
        $BACKGROUND_IMAGE
}

#perform cleanup and exit
if ! swww query; then
     rm -rf /run/user/$UID/swww-*.socket
     swww-daemon &
fi

load_wp
