close_when_open = false
theme = "catppucin"
force_keyboard_focus = true

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl m"]
resume_last_query = ["ctrl r"]
quick_activate = ["F1", "F2", "F3", "F4"]

[providers]
default = [
  "desktopapplications", "menus:screenshots", "menus:power"
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = ":"
provider = "runner"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "?"
provider = "websearch"

[[providers.prefixes]]
prefix = ";"
provider = "clipboard"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date

[providers.actions]

archlinuxpkgs = [
  { action = "install", bind = "Return", default = true },
  { action = "remove", bind = "ctrl d" },
]

"menus:twitch" = [
    { action = "stream", bind = "Return", default = true, label = "Launch Stream" },
    { action = "chat", bind = "ctrl c", label = "Open Chat" },
    { action = "both", bind = "ctrl f", label = "Stream + Chat" },
]

"menus:wallpaperpicker" = [
    { action = "set", bind = "Return", default = true, label = "Set Wallpaper" },
]

"menus:screenshots" = [
    { action = "view", bind = "Return", default = true, label = "View Screenshot" },
    { action = "annotate", bind = "Return" , label = "Annotate last screenshot"},
    { action = "toggle_screenrecord", bind = "Return", label = "Toggle Screen Recording" },
    { action = "screenshot", bind = "Return", label = "Take Screenshot" },
]

# [builtins.translation]
# delay = 1000
# weight = 5
# name = "translation"
# icon = "accessories-dictionary"
# placeholder = "Translation"
# switcher_only = true
# provider = "googlefree"

# [[plugins]]
# name = "aiprompts"
# src = "node ~/.dotfiles/config/hypr/themes/2024/dots/walker/scripts/aiprompts.cjs"
# placeholder = "Select a prompt"
# show_sub_when_single = true
# show_icon_when_single = true
# switcher_only = true
# parser = "json"
