close_when_open = false
theme = "catppucin"
force_keyboard_focus = true

[shell]
anchor_top = true
anchor_bottom = true
anchor_left = true
anchor_right = true

[placeholders]
"default" = { input = "Search", list = "No Results" } # placeholders for input and empty list, key is the providers name, so f.e. "desktopapplications" or "menus:other"

[keybinds]
close = ["Escape"]
next = ["Down"]
previous = ["Up"]
toggle_exact = ["ctrl m"]
resume_last_query = ["ctrl r"]
quick_activate = ["F1", "F2", "F3", "F4"]

[providers]
default = [
  "desktopapplications"
] # providers to be queried by default
empty = ["desktopapplications"] # providers to be queried when query is empty

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = ":"
provider = "runner"

[[providers.prefixes]]
prefix = "."
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "?"
provider = "websearch"

[[providers.prefixes]]
prefix = ";"
provider = "clipboard"

[providers.clipboard]
time_format = "%d.%m. - %H:%M" # format for the clipboard item date

[providers.actions]

archlinuxpkgs = [
  { action = "install", bind = "Return", default = true },
  { action = "remove", bind = "ctrl d" },
]

twitch = [
    { action = "launch", bind = "Return", default = true },
]

wallpaperpicker= [
    { action = "set", bind = "Return", default = true },
]

# [builtins.windows]
# weight = 5
# icon = "view-restore"
# name = "windows"
# placeholder = "Windows"
# show_icon_when_single = true
# prefix = "[]"

# [builtins.translation]
# delay = 1000
# weight = 5
# name = "translation"
# icon = "accessories-dictionary"
# placeholder = "Translation"
# switcher_only = true
# provider = "googlefree"

# [[plugins]]
# name = "twitch"
# src = "node ~/.dotfiles/config/hypr/themes/2024/dots/walker/scripts/twitch.cjs"
# placeholder = "Select a live stream"
# show_sub_when_single = true
# show_icon_when_single = true
# switcher_only = true
# parser = "json"
#
# [[plugins]]
# name = "wallpaper"
# src = "node ~/.dotfiles/config/hypr/themes/2024/dots/walker/scripts/wallpaper.cjs"
# placeholder = "Select a wallpaper"
# show_sub_when_single = false
# show_icon_when_single = true
# switcher_only = true
# theme = "catppucin-image-only"
# theme_base = "catppucin"
# parser = "json"
#
# [[plugins]]
# name = "aiprompts"
# src = "node ~/.dotfiles/config/hypr/themes/2024/dots/walker/scripts/aiprompts.cjs"
# placeholder = "Select a prompt"
# show_sub_when_single = true
# show_icon_when_single = true
# switcher_only = true
# parser = "json"
