#!/bin/sh

if [ ! -d "/sys/class/power_supply/BAT0" ]; then
    echo "No battery found. Exiting."
    exit 0
fi

prev_bat=`cat /sys/class/power_supply/BAT0/capacity`

while true
do
    curr_bat=`cat /sys/class/power_supply/BAT0/capacity`
    if [ $curr_bat -eq 100 && $prev_bat -lt 100 ]; then
        notify-send "Fully charged" "Level: ${curr_bat}%"
    elif [ $curr_bat -le 20 && $prev_bat -gt 20 ]; then
        notify-send --urgency=CRITICAL "Battery Low" "Level: ${curr_bat}%"
    elif [ $curr_bat -le 10 && $prev_bat -gt 10 ]; then
        notify-send --urgency=CRITICAL "Battery Low" "Level: ${curr_bat}%"
    fi
    prev_bat=$curr_bat
    sleep 60
done
