#!/bin/sh

case $1'' in
'status') 
    pkg_updates=$(yay -Sup | wc -l)
    printf '{\"text\":\"%s\",\"tooltip\":\"%s updates available"}' "${pkg_updates}" "${pkg_updates}"
    ;;
'check')
    [ $(yay -Sup | wc -l) -gt 0 ]
    exit $?
    ;;
'upgrade')
    foot_wrapper -e yay -Syu
    ;;
esac
