#!/bin/sh

function app_launcher(){
    wofi --show drun
}

function audio_switcher(){
    outputs=$(pactl --format json list sinks | jq '.[] |  {id: .index, desc: .description}' | jq -s '.')

    selection=$(echo $outputs | jq -r '.[] | .desc' | wofi --show dmenu)
    ouput_id=$(echo $outputs | jq -r ".[] | select(.desc == \"$selection\") | .id")

    if [ -n "$ouput_id" ]; then
        pactl set-default-sink $ouput_id
    fi
}

function wifi_menu(){
    nm-connection-editor &
}

doc() {
    echo "Usage:
    set_env [Options]

    Options:
        application_launcher    Runs wofi application launcher
        wifi                    Runs wofi wifi menu"
}


killall wofi

case $1 in 
  application_launcher) app_launcher   ;;
  wifi)                 wifi_menu   ;;
  audio_switcher)       audio_switcher ;;
  *) doc                            ;;
esac
