#!/bin/sh

# This script focuses a window based on its title or class name.
# Usage: focus_window "Window Title or Class Name"

window=$(hyprctl -j clients)

# run on dmenu to select a window
selected_window=$(echo "$window" | jq -r '.[].title' | walker -d -i "Select window to focus:")
if [ -z "$selected_window" ]; then
    echo "No window selected."
    exit 1
fi

# Extract title or class from the selected window
address=$(echo "$window" | jq -r '.[$selected_window | tonumber].address' --arg selected_window "$selected_window")
hyprctl dispatch focuswindow address:$address
