#!/bin/sh

pkill -x waybar

if [ -f "$WAYBAR_CONFIG_PATH" ]; then
    USER_CONFIG=$WAYBAR_CONFIG_PATH
fi

if [ -f "$WAYBAR_STYLE_PATH" ]; then
    USER_STYLE=$WAYBAR_STYLE_PATH
fi

if [ -z "$HYPR_CONFIG_PATH" ]; then
    waybar
else
    config=${USER_CONFIG:-"$HYPR_CONFIG_PATH/themes/2024/dots/waybar/config.jsonc"}
    envsubst < $(echo $config) > /tmp/waybar-config.jsonc
    waybar -c /tmp/waybar-config.jsonc \
        -s "${USER_STYLE:-"$HYPR_CONFIG_PATH/themes/2024/dots/waybar/style.css"}"
fi
