#!/bin/bash

# prevent multiple instances of waybar from running at the same time
lock_file="$XDG_RUNTIME_DIR/waybar.lock"
exec 200>$lock_file
flock -n 200 || exit 0

pkill -x waybar
sleep 0.5

# Set WAYLAND_DISPLAY to the first available Wayland socket if not already set
echo "Current WAYLAND_DISPLAY: $WAYLAND_DISPLAY" >/tmp/waybar_start
if [ -z "$WAYLAND_DISPLAY" ] || [ "${WAYLAND_DISPLAY#wayland-}" = "$WAYLAND_DISPLAY" ]; then
    socket=$(find "$XDG_RUNTIME_DIR" -maxdepth 1 -type s -name "wayland-*" | head -n 1)
    echo "Found Wayland socket: $socket" >>/tmp/waybar_start
    if [ -n "$socket" ]; then
        export WAYLAND_DISPLAY=$(basename "$socket")
    else
        echo "No Wayland socket found in $XDG_RUNTIME_DIR" >>/tmp/waybar_start
        echo "No Wayland socket found in $XDG_RUNTIME_DIR"
        exit 1
    fi
fi

if [ -f "$WAYBAR_CONFIG_PATH" ]; then
    USER_CONFIG=$WAYBAR_CONFIG_PATH
fi

if [ -f "$WAYBAR_STYLE_PATH" ]; then
    USER_STYLE=$WAYBAR_STYLE_PATH
fi

if [ -z "$DOTFILES_PATH" ]; then
    uwsm app -- waybar
else
    config=${USER_CONFIG:-"$DOTFILES_PATH/config/waybar/config.jsonc"}
    envsubst <$(echo $config) >/tmp/waybar-config.jsonc
    uwsm app -- waybar -c /tmp/waybar-config.jsonc \
        -s "${USER_STYLE:-"$DOTFILES_PATH/config/waybar/style-$HYPR_THEME.css"}"
fi

# Release lock
flock -u 200
exec 200>&-
