#!/bin/sh

# Get random wallpaper from the specified directory and get only jpg/png files
wallpaper=$(find "$WALLPAPERS_PATH" -type f \( -iname "*.jpg" -o -iname "*.png" \) | shuf -n 1)

if [ ! -f /tmp/hyprpaper_runtime.conf ]; then
    cat > /tmp/hyprpaper_runtime.conf <<EOF
wallpaper {
    monitor =
    path = $wallpaper
    fit_mode = cover
}
EOF
fi

# Launch hyprpaper with the selected wallpaper
pidof hyprpaper || hyprpaper -c /tmp/hyprpaper_runtime.conf &
