#!/usr/bin/env sh
set -x

pgrep wf-recorder
status=$?

countdown() {
  for i in 3 2 1; do
    notify "Recording in $i" -t 1000
    sleep 1
  done
}


notify() {
    line=$1
    shift    
    notify-send "Recording" "${line}" -i /usr/share/icons/Papirus-Dark/32x32/devices/camera-video.svg $*
}

if [ $status != 0 ]; then
    target_path=$(xdg-user-dir VIDEOS)
    timestamp=$(date +'recording_%Y%m%d-%H%M%S')

    notify "Select a region to record" -t 1000
    area=$(slurp)

    countdown

    if [ "$1" = "-a" ]; then
        wf-recorder --audio -g "$area" --file="$target_path/$timestamp.mp4" 
    else
        wf-recorder -g "$area" -c libvpx --codec-param="qmin=0" --codec-param="qmax25" --codec-param="cfr=4" --codec-param="b:v=1M" --file="$target_path/$timestamp.wedm" 
    fi

    notify "Finished recording"
else
    pkill --signal SIGINT wf-recorder
fi
