#!/bin/bash

set -e -o pipefail

function opterr() { 
    echo >&2 "stream: Unknown option '$1'" 
}

chat="false"
video="true"
menu="false"
while (( $# )); do
    case $1 in
        -c|--chat)          chat="true"                  ;;
        -n|--no-video)      video="false"                ;;
        -m|--dmenu)         menu="true"                  ;;
        -*)                 opterr $1 && return 2        ;;
        *)                  selected_channel=$1; break   ;;
    esac
    shift
done

if [ -z "$selected_channel" ]; then
    if [ $menu == "true" ]; then
        selected_channel=$(livestream-ctl list | jq -r '.[] | .channel' | walker -d)
    else
        selected_channel=$(livestream-ctl select)
    fi
fi

# Prompt to choose a channel
if [ -z "$selected_channel" ]; then
    echo "No live channel selected"
    exit 1
fi

if [ $video == "true" ]; then
    echo "Lauching stream of $selected_channel"
    livestream-ctl launch $selected_channel
fi

ACCESSTOKEN=$(cat "$HOME/.cache/livestream/twitch_credentials.json" | jq -r '.access_token') 2> /dev/null
if [ $chat == "true" ]; then
    # echo "oauth:$ACCESSTOKEN"
    TWT_TOKEN="oauth:$ACCESSTOKEN" twt -c $selected_channel
fi
