#!/usr/bin/env zsh

# This script is used to set the wallpaper for the active monitor
wallpaper="$1"

if [ ! -f "$1" ]; then
    if [ -z "$WALLPAPERS_PATH" ]; then
        echo "WALLPAPERS_PATH is not set"
        exit 1
    fi
    exit 1
fi

active_monitor=$(hyprctl monitors -j | jq  -r '.[] | select(.focused) | .name')
echo "Active monitor: $active_monitor"
echo "Loading" $wallpaper

# hyprctl hyprpaper unload all
hyprctl hyprpaper preload $wallpaper
hyprctl hyprpaper wallpaper "$active_monitor,$wallpaper"
