#!/usr/bin/env zsh

# This script is used to set the wallpaper for the current session

wallpaper="$1"

if [ ! -f "$1" ]; then
    if [ -z "$WALLPAPERS_PATH" ]; then
        echo "WALLPAPERS_PATH is not set"
        exit 1
    fi
    exit 1
    # format_string="echo 'img:${WALLPAPERS_PATH}/%s:text:'"
    # wallpaper_selected="$(ls $WALLPAPERS_PATH | wofi --pre-display-cmd "$format_string" -c "$HOME/.config/wofi/config_img")"
    # if [ -z "$wallpaper_selected" ]; then
    #     echo "No wallpaper selected"
    #     exit 1
    # fi
    # wallpaper=$WALLPAPERS_PATH/$wallpaper_selected
fi

echo "Loading" $wallpaper

hyprctl hyprpaper unload all
hyprctl hyprpaper preload $wallpaper
hyprctl hyprpaper wallpaper ",$wallpaper"
